server:
  ip: localhost
  port: 9091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/new_springboot?serverTimezone=GMT%2b8
    username: root
    password: zzlde500
  # springboot 设置文件上传大小和请求文件大小
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件

#打印修改的sql语句log
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


files:
  upload:
    path: /Users/zengzl/Desktop/springboot_0321/src/main/resources/static/files/

